version: '3'

services:
  ghost:
    image: ghost:5.90.0
    restart: always
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      url: https://adarshandkirsten.com
      NODE_ENV: production
      FORCE_HTTPS: true
      mail__transport: SMTP
      mail__options__service: Mailgun
      mail__options__host: smtp.mailgun.org
      mail__options__port: 465
      mail__options__secure: 'true'
      mail__options__auth__user: ${SMTP_USERNAME}
      mail__options__auth__pass: ${SMTP_PASSWORD}
      mail__from: 'Adarsh and Kirsten <noreply@adarshandkirsten.com>'
      MAX_FILE_SIZE: 50000000  # 50MB in bytes
    volumes:
      - ./content:/var/lib/ghost/content
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ghost
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ghost-content:
  mysql_data:
